=== TALBARA/talbara.github.io/XML/Soporte.dtd
<!ELEMENT soporte (contacto,metodosDePago)>
<!ELEMENT contacto (telefono,correoElectronico)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT correoElectronico (#PCDATA)>
<!ELEMENT metodosDePago (pago+)>
<!ELEMENT pago (#PCDATA)>

=== TALBARA/talbara.github.io/XML/Soporte.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE soporte SYSTEM "Soporte.dtd">
<soporte>
    <contacto>
        <telefono>912387648</telefono>
        <correoElectronico>supportApp@telefonica.com</correoElectronico>
    </contacto>
    <metodosDePago>
        <pago>PayPal</pago>
        <pago>Visa</pago>
        <pago>MasterCard</pago>
    </metodosDePago>
</soporte>
